### ISSUE TITLE
Add dynamic meta tags and information

### ISSUE THREAD

**Issue by vishnup95** [sepehr1313/react-ssr-apollo-boilerplate#2]
Hi @sepehr1313,

Good boilerplate! Can you please add react-helmet for dynamic meta information. I tried, but seem to be unsuccessfull. 
Dynamic meta tags are a great addition to SSR app. Please consider adding this. 

Also, can you add a section on deployment. I can't seem to deploy this to heroku no matter what I try.

**Comment by vishnup95** [comment]
Just for an update, did manage to update with react helmet. Still an issue remains. Don't know if everything I setup is correct.

**src/server/middleWare/serverRenderer.tsx**
`
renderToStringWithData(Application).then((content) => {
    const initialApolloState = client.extract();
    return res.send(
      '<!doctype html>' +
        renderToStaticMarkup(
          <Html
            scripts={[res.locals.assetPath('bundle.js'), res.locals.assetPath('vendor.js')]}
            initialApolloState={JSON.stringify(initialApolloState)}
            helmet = {Helmet.renderStatic()}
          >
            {content}
          </Html>
        )
    );
  });
};
`

**Comment by vishnup95** [comment]
Just an update on the same. Managed to implement the same using react-helmet. An issue still remains. 

**serverRenderer.tsx**

```
renderToStringWithData(Application).then((content) => {
    const initialApolloState = client.extract();
    return res.send(
      '<!doctype html>' +
        renderToStaticMarkup(
          <Html
            scripts={[res.locals.assetPath('bundle.js'), res.locals.assetPath('vendor.js')]}
            initialApolloState={JSON.stringify(initialApolloState)}
            helmet = {Helmet.renderStatic()}
          >
            {content}
          </Html>
        )
    );
  });
};
```

**HTML.tsx**

```
<head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link
        href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap"
        rel="stylesheet"
      />
      {helmet.title.toString()}
      {helmet.meta.toString()}
      <script
        dangerouslySetInnerHTML={{
          __html: `window.__APOLLO_STATE__ = ${initialApolloState}`,
        }}
      />
</head>
```

This results in meta changes due to client components. The problem is that somehow the meta information is shown as HTML in the page. 

![localhost_3000_about](https://user-images.githubusercontent.com/50899727/89711094-b0f68a80-d9a5-11ea-95b0-b5f4e201e743.png)

**Comment by frntendev** [comment]
Hi @vishnup95 Thanks for raising this. The react-helmet is now added :)

**Comment by vishnups95** [comment]
@sepehr1313 Thanks. Could you also please add some explanation on how to deploy the SSR app. I am a beginner on this, and some help would be much appreciated.
